@startuml
用户 -> 活动组件: 1: 咨询可用活动
活动组件 -> 活动组件: 1.1: 活动准入校验
活动组件 -> 人群组件: 1.1.1: 黑白名单校验
活动组件 <-- 人群组件: 1.1.2:
活动组件 -> 规则组件: 1.1.3: 规则准入校验
活动组件 <-- 规则组件: 1.1.4:
活动组件 -> 计次组件: 1.1.5: 参与计次校验
活动组件 <-- 计次组件: 1.1.6:
活动组件 -> 活动组件: 1.2: 构造可用活动列表
用户 <-- 活动组件: 1.3: 返回咨询结果
@enduml