@startuml
用户 -> 活动组件: 1: 活动申请
活动组件 -> 活动组件: 1.1: 活动申请单落地
活动组件 -> 活动组件: 1.2: 活动准入校验
活动组件 -> 人群组件: 1.3: 黑白名单校验
活动组件 <-- 人群组件: 1.4:
活动组件 -> 规则组件: 1.5: 规则准入校验
活动组件 <-- 规则组件: 1.6
活动组件 -> 计次组件: 1.7: 参与计次检查
活动组件 <-- 计次组件: 1.8:
活动组件 -> 计次组件: 1.9: 参与计次累计
活动组件 <-- 计次组件: 1.10:
活动组件 -> 活动组件: 1.11: 中奖概率计算
活动组件 -> 计次组件: 1.12: 活动中奖计次检查
活动组件 <-- 计次组件: 1.13:
活动组件 -> 奖品组件: 1.14: 奖品查询
活动组件 <-- 奖品组件: 1.15: 返回可用奖品列表
活动组件 -> 活动组件: 1.16: 通过择奖算法确认奖品
活动组件 -> 奖品组件: 1.17: 奖品金额计算
活动组件 <-- 奖品组件: 1.18: 返回奖品金额
活动组件 -> 风控组件: 1.19: 风控咨询，带奖品金额
活动组件 <-- 风控组件: 1.20: 返回风控结果
活动组件 -> 奖品组件: 1.21: 奖品金额调整(依据风控结果)
活动组件 <-- 奖品组件: 1.22: 返回奖品金额
活动组件 -> 活动组件: 1.23: 发奖单落地
活动组件 -> 活动组件: 1.24: 更新活动申请单为preprocess
活动组件 -> 计次组件: 1.25: 活动中奖计次累计
活动组件 <-- 计次组件: 1.26:
活动组件 -> 活动组件: 1.27: 更新活动申请单为award
活动组件 -> 预算组件: 1.28: 预算扣减
活动组件 <-- 预算组件: 1.29:
活动组件 -> 奖品组件: 1.30: 执行发奖
活动组件 <-- 奖品组件: 1.31: 返回发奖结果
活动组件 -> : 1.32: 发奖事件
活动组件 -> 活动组件: 1.33: 更新活动申请单为success
活动组件 <-- 用户: 1.34: 返回申请结构
@enduml